#!/usr/bin/env bash
# Set up and start a local Fiber Network node for NERVE development.
#
# The Fiber node exposes:
#   RPC:  http://localhost:8227  (FIBER_RPC_URL)
#   P2P:  tcp/8228               (FIBER_P2P_PORT)
#
# Prerequisites:
#   - Docker installed and running
#   - AGENT_PRIVATE_KEY set (the same key as nerve-core, or a separate Fiber key)
#   - CKB testnet reachable (FIBER_CKB_RPC or defaults to testnet.ckb.dev)
#
# Usage:
#   source .env && ./scripts/setup_fiber.sh [--reset]
#
# After running, source .env.fiber to export FIBER_RPC_URL, FIBER_NODE_ID.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DATA_DIR="$ROOT_DIR/fiber-data"
RPC_PORT="${FIBER_RPC_PORT:-8227}"
P2P_PORT="${FIBER_P2P_PORT:-8228}"
CKB_RPC="${FIBER_CKB_RPC:-https://testnet.ckb.dev/rpc}"
CKB_WS="${FIBER_CKB_WS:-wss://testnet.ckb.dev/ws}"
CURRENCY="${FIBER_CURRENCY:-Fibt}"

RESET="${1:-}"

step() { echo; echo "── $* ──"; }
ok()   { echo "   OK: $*"; }

# ── Reset ──────────────────────────────────────────────────────────────────────

if [[ "$RESET" == "--reset" ]]; then
	step "Resetting Fiber data dir"
	rm -rf "$DATA_DIR"
	ok "Removed $DATA_DIR"
fi

mkdir -p "$DATA_DIR"

# ── Write config ───────────────────────────────────────────────────────────────

step "Writing Fiber node config"
cat > "$DATA_DIR/config.toml" <<TOML
# Fiber Network node config — generated by setup_fiber.sh

[fiber]
announced_node_name = "nerve-node"
listening_addr = "/ip4/0.0.0.0/tcp/${P2P_PORT}"
public_key = ""   # generated on first start from the keystore

[chain]
ckb_rpc_url = "${CKB_RPC}"
ckb_websocket_url = "${CKB_WS}"

[rpc]
listening_addr = "0.0.0.0:${RPC_PORT}"

[invoice]
currency = "${CURRENCY}"
TOML
ok "Config written to $DATA_DIR/config.toml"

# ── Import key (if AGENT_PRIVATE_KEY is set) ──────────────────────────────────

if [[ -n "${AGENT_PRIVATE_KEY:-}" ]]; then
	KEY="${AGENT_PRIVATE_KEY#0x}"
	echo "$KEY" > "$DATA_DIR/key"
	chmod 600 "$DATA_DIR/key"
	ok "Private key written to $DATA_DIR/key"
fi

# ── Start Fiber node via Docker ────────────────────────────────────────────────

step "Starting Fiber node (Docker)"
if docker ps --format '{{.Names}}' | grep -q '^nerve-fiber$'; then
	echo "   Container nerve-fiber is already running."
else
	docker run -d \
		--name nerve-fiber \
		--restart unless-stopped \
		-p "${RPC_PORT}:${RPC_PORT}" \
		-p "${P2P_PORT}:${P2P_PORT}" \
		-v "${DATA_DIR}:/data" \
		nervosnetwork/fiber:latest \
		fnn --config-dir /data 2>/dev/null \
	|| docker start nerve-fiber 2>/dev/null \
	|| { echo "   Note: Docker image nervosnetwork/fiber:latest may not exist yet."; echo "   Starting fiber-pay instead (if installed)..."; }
fi

# ── Wait for RPC ───────────────────────────────────────────────────────────────

step "Waiting for Fiber RPC to be ready"
for i in $(seq 1 20); do
	if curl -sf -X POST "http://localhost:${RPC_PORT}" \
		-H "Content-Type: application/json" \
		-d '{"jsonrpc":"2.0","id":1,"method":"info_node_info","params":{}}' \
		>/dev/null 2>&1; then
		ok "Fiber RPC is up at http://localhost:${RPC_PORT}"
		break
	fi
	echo "   Waiting... ($i/20)"
	sleep 3
done

# ── Fetch node info ────────────────────────────────────────────────────────────

step "Fetching node info"
NODE_INFO=$(curl -sf -X POST "http://localhost:${RPC_PORT}" \
	-H "Content-Type: application/json" \
	-d '{"jsonrpc":"2.0","id":1,"method":"info_node_info","params":{}}' 2>/dev/null || echo '{}')
NODE_ID=$(echo "$NODE_INFO" | grep -o '"node_id":"[^"]*"' | cut -d'"' -f4 || true)

if [[ -n "$NODE_ID" ]]; then
	ok "Node ID: $NODE_ID"
	# Write to .env.fiber for sourcing
	cat > "$ROOT_DIR/.env.fiber" <<ENV
FIBER_RPC_URL=http://localhost:${RPC_PORT}
FIBER_P2P_PORT=${P2P_PORT}
FIBER_NODE_ID=${NODE_ID}
FIBER_CURRENCY=${CURRENCY}
ENV
	ok "Written to .env.fiber — source it to export Fiber env vars"
else
	echo "   Could not read node ID (node may still be starting)."
fi

echo
echo "==> Fiber node started."
echo "    RPC:  http://localhost:${RPC_PORT}"
echo "    P2P:  tcp/${P2P_PORT}"
echo "    Logs: docker logs nerve-fiber"
